apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cqwj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-cqwj@sha256:5ebe7febb649737627816bdede6dc29d9a512a0fb94ca34bd129544fd0488306
        name: my-nodejs
        resources: {}
status: {}
